AWSTemplateFormatVersion: "2010-09-09"
Metadata: 
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "Project Name"
        Parameters: 
          - PJName
      - Label: 
          default: "Environment Configuration"
        Parameters: 
          - Env
      - Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCID
          - PrivateSubnet
          - SecurityGroupId
      - Label: 
          default: "Instance Configuration"
        Parameters: 
          - Ec2ImageId
          - EC2InstanceProfile
          - InstanceType

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  PJName:
      Type: String

  Env:
    Type: String
    AllowedValues:
      - prod
      - stg
      - dev
  VPCID:
    Type: AWS::EC2::VPC::Id

  PrivateSubnet:
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  
  EC2InstanceProfile:
    Type: String
  
  Ec2ImageId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - m1.small


# ------------------------------------------------------------#
# EC2
# ------------------------------------------------------------#
Resources:
    EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref Ec2InstanceType
      SubnetId: !Ref PrivateSubnet
      ImageId: !Ref Ec2ImageId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      IamInstanceProfile: !Ref EC2InstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      EbsOptimized: true
      SourceDestCheck: true
      Tags:
        - Key: Name
          Value: !Sub ${PJName}-${Env}-EC2