AWSTemplateFormatVersion: "2010-09-09"
Metadata: 
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "Project Name"
        Parameters: 
          - PJName
      - Label: 
          default: "Environment Configuration"
        Parameters: 
          - Env
      - Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCID

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  VPCID:
    Type: AWS::EC2::VPC::Id
  PJName:
      Type: String
  Env:
    Type: String

# ------------------------------------------------------------#
# Endpoint SG
# ------------------------------------------------------------# 
Resources:
  SSMEndpointSG:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        VpcId: !Ref VPCID
        GroupName: !Sub ${PJName}-${Env}-endpoint-sg
        GroupDescription: !Sub ${PJName}-${Env}-endpoint-sg
        Tags:
          - Key: Name
            Value: !Sub ${PJName}-${Env}-endpoint-sg
  SSMEndpointSGIngress1:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref SSMEndpointSG
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 10.0.0.0/24

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------# 
Outputs:
  SSMEndpointSG:
    Value: !Ref SSMEndpointSG
    Export: 
      Name: !Sub ${PJName}-${Env}-endpoint-sg